# troFFM
# Utility functions, environment, etc.
troFFMInitialize <- function(sourcefile="M.xlsx",
                             ShowInfoMsg=TRUE,
                             ShowWarningMsg=TRUE) {
    if (!exists("FFMenv")) FFMenv <<- new.env()
    load(file.path(SOURCE.DIR,'PSI.RData'))
    assign("PSI",PSI,envir=FFMenv)
    assign("FFMtol",0.0001,envir=FFMenv)
    assign("ShowInfoMsg",ShowInfoMsg,envir=FFMenv)
    assign("ShowWarningMsg",ShowWarningMsg,envir=FFMenv)
    assign("sourcefile",sourcefile,envir=FFMenv)
    assign("DefaultFirst.acp",2000,envir=FFMenv)
    new.tro()
    }

FFMtol <- function() get("FFMtol",envir=FFMenv)
troDefaultFirst.acp<-function() get("DefaultFirst.acp",envir=FFMenv)

getPSI <- function() {
    if (!exists("FFMenv")) {
        FFMenv <<- new.env()
        load('PSI.RData') 
        assign("PSI",PSI,envir=FFMenv)
        }
    else get("PSI",envir=FFMenv)
    }

getPSItable <- function() {
    if (!exists("FFMenv")) {
        FFMenv <<- new.env()
        # PSI.RData holds the matrix, PSI, of normal.rawmoment.ratio's for 
        #   sequences of alpha (in particular, negative values) and cv.
        # PSI was previously generated by simulation. 
        # See PSI.build in PSI.r
        load('PSI.RData')
        # Make PSI "globally available" via the 'get' command
        assign("PSItable",PSI,envir=FFMenv) 
        }
    else get("PSItable",envir=FFMenv)
    }

getShowInfoMsg.ffm<-function() get("ShowInfoMsg",envir=FFMenv)
getShowWarningMsg.ffm<-function() get("ShowWarningMsg",envir=FFMenv)
getsourcefile.ffm<-function() get("sourcefile",envir=FFMenv)

ffmInfoMsg<-function(...,show.msg=FALSE) {
    if (missing(show.msg)) {
#        if (getShowInfoMsg.ffm()) cat(paste(...,"\n"))
        if (getShowInfoMsg.ffm()) cat(...,"\n")
        }
#    else if (show.msg) cat(paste(...,"\n"))
    else if (show.msg) cat(...,"\n")
    }

printx.ffm <- function(x) {
print.default(x)
print(data.frame(
    age   =sapply(x,function(y) y$age), 
    endage=sapply(x,function(y) y$endage),
    ata   =sapply(x,function(y) y$ata), 
    sef   =sapply(x,function(y) y$sef), 
    sigma =sapply(x,function(y) y$sigma), 
    alpha =sapply(x,function(y) y$alpha)))
}

print.ffm<-function (x, digits = max(3, getOption("digits") - 3), ...) {
    cat("DevPer:", paste(x$age, x$endage, sep="-"),
        "ata=", x$ata, "sef=", x$sef, ", sigma=", x$sigma, 
        "df=",x$df, ", alpha=", x$alpha,
        "\n")
    invisible(x)
    }
print.ffmlist<-function(x) print(troSummarize.LM(unclass(x)))

SS_del_loglikeli2.ffm <- function(f,sigma2,alpha,Ck,Ck1) {
    n<-length(Ck)
    (sum(f*Ck^(2-alpha)-Ck1*Ck^(1-alpha)))^2 +
        (-n*sigma2+sum(Ck^-alpha*(Ck1-f*Ck)^2))^2 +
        (sum(log(Ck)*((Ck1-f*Ck)^2*Ck^-alpha-sigma2)))^2
    }
SSdelLL2 <- function(f,sigma2,alpha,x,y) {
    fffm <- f.ffm(alpha,x,y)
    T1 <- f-fffm
    sigma2ffm <- sigma2.ffm(f,alpha,x,y)
#    sigma2ffm <- sigma2.ffm(fffm,alpha,x,y)
    T2 <- sigma2-sigma2ffm
#    T3 <- sum(log(x)*((y-f*x)^2/x^-alpha-sigma2))
    n<-length(x)
    T3 <- -n/2/sigma2*sum(log(x)*(y-f*x)^2/x^alpha)-.5*sum(log(x))
#    T3 <- -n/2/sigma2ffm*sum(log(x)*(y-fffm*x)^2/x^alpha)-.5*sum(log(x))
    T1^2+T2^2+T3^2
    }
SSdelLL2B <- function(f,sigma2,alpha,x,y) {
    fffm <- f.ffm(alpha,x,y)
    T1 <- f-fffm
    sigma2ffm <- sigma2.ffm(fffm,alpha,x,y)
    T2 <- sigma2-sigma2ffm
    T3 <- sum(log(x)*((y-fffm*x)^2/x^-alpha-sigma2ffm))
    T1^2+T2^2+T3^2
    }
SSdelLL2v <- function(v,...) SSdelLL2(v[1],v[2],v[3],...)
optim_f_sigma_alpha <- function(v,...) SS_del_loglikeli2.ffm(v[1],v[2],v[3],...)

del_LLalpha2A.ffm <- function(alpha,Ck,Ck1) {
    n<-length(Ck)
    # First, calc f
    f <- f.ffm(alpha,Ck,Ck1)
    sigma2 <- sigma2.ffm(f,alpha,Ck,Ck1)
    (sum(log(Ck)*((Ck1-f*Ck)^2/Ck^alpha - sigma2)))^2
    }

del_LLalpha2B.ffm <- function(alpha,Ck,Ck1) {
    n<-length(Ck)
    # First, calc f
    f <- f.ffm(alpha,Ck,Ck1)
    sigma2 <- sigma2.ffm(f,alpha,Ck,Ck1)
    (sum(log(Ck)*((Ck1-f*Ck)^2/(Ck^alpha*sigma2) - 1)))^2
    }

#LL.ffm <- function(alpha,Ck,Ck1) {
#    n <- length(Ck)
#    f <- f.ffm(alpha,Ck,Ck1)
#    sigma2 <- sigma2.ffm(f,alpha,Ck,Ck1)
#    T1<--n/2*log(2*pi)
#    T2<--.5*sum(alpha*log(Ck))
#    T3<--n/2*log(sigma2)
#    T4<--.5/sigma2*sum((Ck1-f*Ck)^2/Ck^alpha)
#prn(data.frame(T1=T1,T2=T3,T3=T3,T4=T4))
#    -n/2*log(2*pi)-.5*sum(alpha*log(Ck))-n/2*log(sigma2)-.5/sigma2*sum((Ck1-f*Ck)^2/Ck^alpha)
#    }
LL.ffm <- function(f,sigma2,alpha,x,y) {
    n<-length(x)
    T1<--n/2*log(2*pi)
    T2<--alpha/2*sum(log(x))
    T3<--n/2*log(sigma2)
    T4<--1/2/sigma2*sum((y-f*x)^2/x^alpha)
    L<-T1+T2+T3+T4
#prn(data.frame(alpha=alpha,f=f,sigma2=sigma2,T1=T1,T2=T2,T3=T3,T4=T4,L=L))
    L
    }
negLLv.ffmB <- function(v,...) -LL.ffm(v[1],v[2],v[3],...)

negLL.ffm <- function(f,sigma2,alpha,x,y) {
    .5*sum(log(2*pi*x^alpha*sigma2)+(y-f*x)^2/x^alpha/sigma2)
    }
negLLnoxy.ffm<- function(f,sigma2,alpha) {
    .5*sum(log(2*pi*x^alpha*sigma2)+(y-f*x)^2/x^alpha/sigma2)
    }

grnegLLv.ffm <- function(v,x,y) {
    f<-v[1]
    sigma2<-v[2]
    alpha<-v[3]
    n<-length(x)
    c(-1/sigma2*sum((y-f*x)*x^(1-alpha)),
      .5*n/sigma2-1/sigma2^2*sum((y-f*x)^2/x^alpha),
      .5*sum(log(x)*(1-(y-f*x)^2/x^alpha/sigma2)))
    }
negLLv.ffm <- function(v,...) negLL.ffm(v[1],v[2],v[3],...)

LL3.ffm <- function(f,sigma2,alpha,x,y) {
    n <- length(x)
    T1<--n/2*log(2*pi)
    T2<--.5*sum(alpha*log(x))
    T3<--n/2*log(sigma2)
    T4<--.5/sigma2*sum((y-f*x)^2/x^alpha)
    T1+T2+T3+T4
    }
LL3v.ffm <- function(v,...) LL3.ffm(v[1],v[2],v[3],...)
negLL3v.ffm <- function(...) -LL3v.ffm(...)

#negLL.ffm <- function(...) -LL.ffm(...)

del_LLalpha2.ffm <- function(alpha,Ck,Ck1) {
    f <- f.ffm(alpha,Ck,Ck1)
    sigma2 <- sigma2.ffm(f,alpha,Ck,Ck1)
    (-.5*sum(log(Ck)) + (.5/sigma2)*sum((Ck1-f*Ck)^2*Ck^-alpha*log(Ck)))^2
    }

f.ffm <- function(alpha,Ck,Ck1) sum(Ck^(1-alpha)*Ck1)/sum(Ck^(2-alpha))

sigma2.ffm <- function(f,alpha,x,y) 
    mean((y-f*x)^2/x^alpha) # *(n<-length(x))/(n-1)

LLsigma.ffmA <- function(alpha,x,y) {
    n<-length(x)
    T1<--n/2*log(2*pi)
    T2<--n/2
    f <- f.ffm(alpha,x,y)
    sigma2 <- sigma2.ffm(f,alpha,x,y)
    T3<--n/2*log(sigma2)
    T4<--alpha/2*sum(log(x))
    L<-T1+T2+T3+T4
#prn(data.frame(alpha=alpha,f=f,sigma2=sigma2,T1=T1,T2=T2,T3=T3,T4=T4,L=L))
    L
    }
negLLsigma.ffm <- function(...) -LLsigma.ffm(...)
LLsigma.ffm <- function(alpha,x,y) {
    n<-length(x)
    T1<--n/2*log(2*pi)
    T2<--alpha/2*sum(log(x))
    f <- f.ffm(alpha,x,y)
    sigma2 <- sigma2.ffm(f,alpha,x,y)
    T3<--n/2*log(sigma2)
    T4<--1/2/sigma2*sum((y-f*x)^2/x^alpha)
    L<-T1+T2+T3+T4
#prn(data.frame(alpha=alpha,f=f,sigma2=sigma2,T1=T1,T2=T2,T3=T3,T4=T4,L=L))
    L
    }
LLalpha.ffm <- function(alpha,x,y) {
    n<-length(x)
    T1<--n/2*log(2*pi)
    T2<--alpha/2*sum(log(x))
    f <- f.ffm(alpha,x,y)
    sigma2 <- sigma2.ffm(f,alpha,x,y)
    T3<--n/2*log(sigma2)
    T4<--1/2/sigma2*sum((y-f*x)^2/x^alpha)
    L<-T1+T2+T3+T4
    L
    }
negLLalpha.ffm<-function(...) -LLalpha.ffm(...)

dfdaB<-function(alpha,x,y)
    -sum(x^(1-alpha)*y)*sum(x^(2-alpha)*log(x)) - sum(x^(1-alpha)*y*log(x))*sum(x^(2-alpha))
    
d2ldf2<-function(x,y,alpha,sigma2=sigma2.FFM(x,y,alpha)) -1/sigma2*sum(x^(2-alpha))

f.FFM <- function(x,y,alpha) sum(x^(1-alpha)*y)/sum(x^(2-alpha))

sigma2.FFM <- function(x,y,alpha,f=f.ffm(alpha,x,y) )
    mean((y-f*x)^2/x^alpha) # *(n<-length(x))/(n-1)

d2lda2<-function(x,y,alpha,f=f.ffm(alpha,x,y),sigma2=sigma2.FFM(x,y,alpha,f))
    -1/2/sigma2*sum((y-f*x)^2*x^-alpha*(log(x))^2)

d2lda2.a1 <- function(alpha,x,y,...) d2lda2(x,y,alpha,...)
d2lda2.a1neg<-function(...) -d2lda2.a1(...)

d2ldfda<-function(x,y,alpha,f=f.ffm(alpha,x,y),sigma2=sigma2.FFM(x,y,alpha,f))
    -1/sigma2*sum((y-f*x)*x^(1-alpha)*log(x))

d2ldsda<-function(x,y,alpha,f=f.ffm(alpha,x,y),sigma2=sigma2.FFM(x,y,alpha,f))
    -1/2/sigma2^2*sum((y-f*x)^2*x^-alpha*log(x))

ds2daA<-function(x,y,alpha,f=f.FFM(x,y,alpha)) 
    -mean(sum((y-f*x)^2*x^-alpha*log(x)))

ds2da<-function(x,y,alpha,f=f.FFM(x,y,alpha)) 
    -mean(sum((y-f*x)^2*x^-alpha*log(x)+(y-f*x)*x^(1-alpha)*dfda(x,y,alpha)))
    
#ve.FFM <- function(x0,

#dveda.FFM <- function(x,y,x0,alpha,sigma2=sigma2.FFM(x,y,alpha),f=f.FFM(x,y,alpha))
#    x0^alpha*ds2da(x,y,alpha)+

dfdaA<-function(alpha,x,y)
    sum(x^(1-alpha)*y)*(sum(x^(2-alpha)))^-2*sum(x^(2-alpha)*log(x)) - 
        sum(x^(1-alpha)*y*log(x))*(sum(x^(2-alpha)))^-1
dfda<-function(x,y,alpha)
    sum(x^(1-alpha)*y)*(sum(x^(2-alpha)))^-2*sum(x^(2-alpha)*log(x)) - 
        sum(x^(1-alpha)*y*log(x))*(sum(x^(2-alpha)))^-1

dldaA<-function(x,y,alpha,f=f.ffm(alpha,x,y),sigma2=sigma2.FFM(x,y,alpha))
    -.5*sum(log(x))+.5/sigma2*sum((y-f*x)^2*x^-alpha*log(x))

dldaA<-function(x,y,alpha,f=f.ffm(alpha,x,y),sigma2=sigma2.FFM(x,y,alpha))
    -.5*sum(log(x))+.5/sigma2*sum((y-f*x)^2*x^-alpha*log(x))
dlda<-function(x,y,alpha,f=f.ffm(alpha,x,y),sigma2=sigma2.FFM(x,y,alpha))
    -.5*sum(log(x)) - 
        n/2/sigma2*ds2da(x,y,alpha) + 
        .5*sigma2^-2*ds2da(x,y,alpha)*sum((y-f*x)^2*x^-alpha) +
        .5/sigma2*sum((y-f*x)^2*x^-alpha*log(x)+2*(y-f*x)*x^(1-alpha)*dfda(x,y,alpha))
        
LBA<-function(alpha,b,x,y)
    -length(x)/2*log(2*pi)-alpha/2*sum(log(x))-.5*sum((y-b*x)^2*x^-alpha)
negLBA.v<-function(v,x,y) -LBA(v[1],v[2],x,y)

b.alpha<-function(alpha,x,y) sum(y*x^(1-alpha))/sum(x^(2-alpha))

LABS2<-function(alpha,b,s2,x,y)
    -(n<-length(x))/2*log(2*pi)-alpha/2*sum(log(x))-n/2*log(s2)-.5/s2*sum((y-b*x)^2*x^-alpha)
negLABS2.v<-function(v,x,y) -LABS2(v[1],v[2],v[3],x,y)

HABS2<-function(alpha,f,sibma2,x,y) optim(c(alpha,fffm,sigma2),negLABS2.v,gr=NULL,x,y,method="BFGS",hessian=T)$hessian

alphaoptimize<-function(x,y) optimize(LLsigma.ffm,interval=c(-100,100),x,y,maximum=TRUE)$max

alphaoptimizeWithHessian<-function(x,y) optim(0,negLLalpha.ffm,gr=NULL,method="BFGS",x,y,hessian=T)

# alphaoptimize(x,y) and alphaoptimizeWithHessian(x,y) give same value for alpha
#   when x and y are the 1st and 2nd columns of the RAA triangle.
#   Hessian = 1.639737
# which is different from what you get when you use optim on the three parameters thus:
#   optim(c(alpha,f.FFM(x,y,alpha),sigma2.FFM(x,y,alpha)),negLABS2.v,gr=NULL,x,y,method="BFGS",hessian=T)$hessian